### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/craft-your-knowledge#1]
## Value Proposition

As a Developer
I want a project starting point, with working CI and CD
so that I can start developing on a base

## Description

Get tech-stack and dependencies ready

## Acceptance Critera

- [ ] npm scripts are working
- [ ] backend structure is ready
- [ ] frontend structure is ready
- [ ] dockerfile is ready
- [ ] .gitignore is ready
- [ ] MongoDB is connected and ready

## Tasks

- [ ] create project
- [ ] create backend with SpringInitilizr
- [ ] create frontend with Vite React Typescript
- [ ] .gitignore
- [ ] MongoDB
- [ ] CI
- [ ] CD

## Complexity Weight

1
