### ISSUE TITLE
openai webclient

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/craft-your-knowledge#11]
## Value Proposition

As a user
I want to be able to see generated AI workshop data in a formatted way
so that my workshops have actual content to discover

## Description

![Image](https://user-images.githubusercontent.com/109807794/256785807-c620db67-8e7e-4d31-ac65-2d19549e1b89.png)

## Acceptance Critera

- [ ] display generated content within the workshops in a user-friendly format
- [ ] content should be meaningful and correctly formatted and displayed in markdown

## Tasks

- [ ] write webclient in backend for the OpenAI API
- [ ] Add `content` property to workshop record
- [ ] build a prompt based on the form data of workshop and send it to the OpenAi API
- [ ] Write the response data into the workshops collection MongoDB
- [ ] Retrieve and display workshop content data in Markdown format in frontend

## Complexity Weight

13
