### ISSUE TITLE
security

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/craft-your-knowledge#12]
## Value Proposition

As a user
I want to be able to set my own progress & likes for workshops
so that I can use my personalized account

## Description

![Image](https://user-images.githubusercontent.com/109807794/256794243-98911809-02c8-49ff-b4f2-527f677ce234.png)

## Acceptance Critera

- [ ] I can see the workshops as a guest
- [ ] I have a login, where i could login into my account
- [ ] As admin user I can create and delete workshops
- [ ] As normal user I can put my like and progress status to workshops
- [ ] As guest user I can only see the list

## Tasks

- [ ] Implement user registration and login functionality using Spring Security
- [ ] Create necessary models and controllers for workshops and users
- [ ] Implement the ability for users to choose and like workshops
- [ ] Write logic for liking and update the count into the workshop record of MongoDB
- [ ] Create roles and only allow admin role on create and delete Endpoints
- [ ] Create Login component in Frontend
- [ ] Display current like count on each workshop
- [ ] Have a guest state of the site, which only shows the list of current workshops
- [ ] Have a normal user state of the site, which shows like and progress in addition to current workshops
- [ ] Have a admin user state of site, which has the create Form and everything else displayed

## Complexity Weight

34
