### ISSUE TITLE
fetch with tokens

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/craft-your-knowledge#13]
## Value Proposition

As a registered user
I want to have tokens associated with my account
so that I can use them to generate workshops

## Description

![Image](https://user-images.githubusercontent.com/109807794/256798050-720aec6c-7785-4b65-874d-f077931c9cb4.png)

## Acceptance Critera

- [ ] Each registered user has 5 tokens initially
- [ ] Tokens are stored in the user account in the database
- [ ] when a suer creates a workshop, one token is consumed
- [ ] Users can only create if they have enough tokens available
- [ ] If a user has no tokens left, they cannot perform any more workshop creations until they have tokens again

## Tasks

- [ ] Add a `tokens` field to the user record in the database to store the number of tokens for each user
- [ ] Initiliaze a user with 5 tokens, when their account is being created
- [ ] create mechanism in backend to track usage of tokens, when a user creates a workshop
- [ ] implement logic to check the number of available tokens before allowing users to create a workshop
- [ ] display current amount of tokens of the user if logged in in the frontend
- [ ] disable the workshop creation functionality for users who have no tokens left and hint them
- [ ] handle how admin role is using tokens

## Complexity Weight

13
