### ISSUE TITLE
prompt engineering 01

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/craft-your-knowledge#15]
## Value Proposition

As a User
I want better workshops and challenges
so that I can enjoy better content

## Description

The prompts and String interpolations are quite basic for now. It should be refined and also feeded with several Examples of different existing workshops as Model Adapter.

## Acceptance Critera

- [ ] Generates an good article about the topic in the designated programming language
- [ ] Generates a coding challenge with basic hinting
- [ ] Article and Challenge should be visually apart from each other

## Tasks

- [ ] Try to prompt JSON output for better content handling
- [ ] make sure that Markdown Output is still being generated, but within a JSON Object
- [ ] make sure that Code Blocks always have language declaration
- [ ] Create static String Data for example workshops for now in Java and JavaScript
- [ ] Add React and Typescript to dropdown menu of create form
- [ ] Add custom language to dropdown menu

## Complexity Weight

14
