### ISSUE TITLE
coding editor with validator

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/craft-your-knowledge#18]
## Value Proposition

As a User
I want to validate my answers to the challenges
so that I can practice the things I learned

## Description

We need an editor so the user can take the challenge

## Acceptance Critera

- [ ] Coding Editor below the Challenge
- [ ] On click my Input can be validated
- [ ] It either approves or denies the user input

## Tasks

- [ ] Add monaco coding editor to frontend
- [ ] Track User-Input in state
- [ ] Create agent for validating user-input
- [ ] parse response to true or false (approved, denied)
- [ ] think about a hinting system

## Complexity Weight

55
