### ISSUE TITLE
read workshop list

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/craft-your-knowledge#2]
## Value Proposition

As a User
I want to see current available workshops
so that I can get an overview of the sites content

## Description

![Image](https://user-images.githubusercontent.com/109807794/255433446-8674590d-116f-4472-bc9f-75f476f8cfd5.png)

## Acceptance Critera

- [ ] See a list of current existing courses

## Tasks

- [ ] Create dummy data in MongoDB Collection `workshops`
- [ ] Write get endpoints, both all and by id
- [ ] fetch get endpoint
- [ ] display data

## Complexity Weight

5
