### ISSUE TITLE
challenge response

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/craft-your-knowledge#20]
## Value Proposition

As a User
I want to have a response upon finishing my challenge
so that I can have feedback

## Description

When submitting a challenge answer, it should return a response if the user passed or failed the challenge. Also there should be further information and feedback about the challenge. When completing the challenge the progress status should be set to completed. 

## Acceptance Critera

- [ ] there is a submit button below the code-editor
- [ ] submitting only works if minimum 100 stables are typed into the code-editor
- [ ] submitting creates a challenge response which is being displayed as pass or failed
- [ ] it also should generate feedback to the user in form of details
- [ ] when there is a response available there should be a show-details button

## Tasks

- [ ] Handle Validation Response further in frontend
- [ ] Evaluate the >>>PASS/FAIL<<< in the response string, display correct data on that
- [ ] remove evaluation string from output
- [ ] Set users progress status to completed, if passed
- [ ] Set users progress status to in_progress if code-editor being touched

## Complexity Weight

21
