### ISSUE TITLE
create workshop

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/craft-your-knowledge#3]
## Value Proposition

As a user
I want to add my own workshops
so that I can share and access it myself

## Description

![Image](https://user-images.githubusercontent.com/109807794/255434020-f3915a45-7d22-482b-8577-826f81066c84.png)

## Acceptance Critera

- [ ] You can make entries in a form
- [ ] When submitting another workshop is being added to the list

## Tasks

- [ ] Create DTO Records and Types
- [ ] Create post endpoint
- [ ] create a form with respective data
- [ ] fetch post endpoint with form data

## Complexity Weight

8
