### ISSUE TITLE
delete workshop

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/craft-your-knowledge#4]
## Value Proposition

As a User
I want to delete workshops
so that I can focus

## Description

![Image](https://user-images.githubusercontent.com/109807794/255434774-97ed2880-f21f-42fa-aeed-31f2cfbbfe03.png)

## Acceptance Critera

- [ ] each workshop element has its own delete button
- [ ] pushing delete, does indeed delete the corresponding element

## Tasks

- [ ] create delete endpoint
- [ ] create delete button
- [ ] fetch delete endpoint

## Complexity Weight

1
