### ISSUE TITLE
update workshop

### ISSUE THREAD

**Issue by Satttoshi** [Satttoshi/craft-your-knowledge#8]
## Value Proposition

As a User
I want to update my workshop status
so that I can switch in between my workshop progress

## Description

![Image](https://user-images.githubusercontent.com/109807794/256254582-7b03a4d0-9e2c-488d-b1e9-d58af9e9da4c.png)

## Acceptance Critera

- [ ] The List now renders a ⭐and the current progress status of the workshop
- [ ] You can like and unlike a workshop with hitting on the ⭐

## Tasks

- [ ] Create Record `UserWithOnlyUsername`
- [ ] Create Record `WorkshopPersonalStatus` 
- [ ] Add `UserWithOnlyUsername` into user property of `WorkshopPersonalStatus`
- [ ] Update Record `Workshop` and include an array of `WorkshopPersonalStatuses`
- [ ] Link ID to `Workshop`
- [ ] Create a new MongoDB Collection `userWorkshopStatus`
- [ ] Create Service & Controller & Repository for `PersonalWorkshopStatus`
- [ ] Write insane Frontend logic

## Complexity Weight

13
